name = "Once Upon A Time"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc064cee4a7deba8c9a3f9fed8ab6d6f4f48c5bcfa40ce0fc26b53b61ce963b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.83"
