#Whether or not to enable the options in this tweak
"Cure tweaks" = true
#A list of potion effects that act like weakness in Zombie Villager curing, separated by a comma (no spaces)
"Weakening Effects" = "minecraft:weakness"
#Whether or not items in the trains_tweaks:curing_items tag should be used to cure weakened Zombie Villagers instead of hardcoded Golden Apples
"Use Curing Tag" = true
#Whether or not items in the trains_tweaks:instant_curing_items tag should be used to cure Zombie Villagers instantly without an effect
"Use Instant Curing Tag" = true
#If enabled, Instant Cures will grant the vanilla Zombie Doctor advancement
#Note that this makes the advancement have a slightly inaccurate description
"Instant Cure Advancement" = true
