#Whether or not to enable the tweaks in this feature
"Difficulty tweaks" = false
#If set to false, the 0.5x (Easy) or 1.5x (Hard) multipliers will not be applied to incoming damage to players
#There are many other, more interesting ways the difficulty setting matters - see below options
"Damage Scaling" = true
#This is a constant modifier to Regional Difficulty
#This value is added to the vanilla calculation. Higher values are more difficult. End result cannot go below 0
#See https://minecraft.wiki/w/Difficulty#Regional_difficulty for more information on calculation and effects
# Default: 0.0
# Range: -10.0 ~ 10.0
"Regional Difficulty Mod" = 0.0
#This is a constant modifier to Special Multiplier AKA Clamped Regional Difficulty
#This value is added to the vanilla calculation (which is influenced by Regional Difficulty). Higher values are more difficult. End result cannot go below 0
#See https://minecraft.wiki/w/Difficulty#Clamped_regional_difficulty for more information on calculation and effects
# Default: 0.0
# Range: -5.0 ~ 5.0
"Special Multiplier Mod" = 0.0
