#Whether or not to enable rarity tweak
"Rarity tweak" = true
#If true, enchantments cannot alter an ItemStack's rarity
"Prevent Enchantment Altering" = true
#If true, any item in one of the following item tags will automatically have its rarity set to that rarity
#trains_tweaks:common, trains_tweaks:uncommon, trains_tweaks:rare, trains_tweaks:epic
"Rarity Tagging" = true
#If enabled, any item that isn't in one of the rarity tags that has had its rarity component modified (or removed) will automatically have its rarity be reset
#Requires Rarity Tagging to be true
"Restore Default Rarity" = false
