#Whether or not to make ocelots tameable into cats by making them trust you
#Note that this does not work exactly like pre-1.14 to ensure the Two by Two advancement is possible
"Tame Ocelots" = true
#Force tamed ocelots to be a specific variant of cat
#set to 'none' to disable
#See https://minecraft.wiki/w/Cat#Entity_data for valid values
"Force Cat Variant" = "none"
