#List of blocks that can be moved along with the top of the pole
movableApexes = ["#minecraft:banners", "#c:chests", "hopper:*", "torch:*", "soul_torch:*", "redstone_torch:*", "campfire:*", "soul_campfire:*"]
#Allows to quickly extend a pole by right-clicking it with a pole item
quickExtension = true
#Number of poles that can be placed(when holding pole items in both hands) / broken(when crouching) at once
# Default: 8
# Range: 1 ~ 128
maxPolesAtOnce = 8

[Painting]
	#These settings are shared between several mods and therefore located in forgeendertech-common.toml
	"whereAreTheSettings?" = ["I've read the hint and understood"]

[SlidingMechanics]
	#Enables/disables sliding mechanics for this type of blocks
	GlassPanes = true
	#Enables/disables sliding mechanics for this type of blocks
	WoodenFences = true
	#Enables/disables sliding mechanics for this type of blocks
	IronBars = true
	#Enables/disables sliding mechanics for this type of blocks
	Chains = true
	#Enables/disables sliding mechanics for this type of blocks
	BambooPlants = true
	#Enables/disables sliding mechanics for this type of blocks
	ModdedFences = true
	#Enables/disables sliding mechanics for this type of blocks
	Posts = true

	[SpeedLimits.MetalPoles]
		#Defines how fast sliding velocity changes
		# Default: 0.04
		# Range: 0.0 ~ 0.1
		acceleration = 0.04
		#Maximum climbing speed up the pole
		# Default: 0.2
		# Range: 0.0 ~ 0.4
		climbing = 0.2
		#Maximum sliding speed down the pole
		# Default: 0.4
		# Range: 0.0 ~ 0.8
		sliding = 0.4
		#Maximum spinning speed around the pole
		# Default: 0.1
		# Range: 0.0 ~ 0.2
		spinning = 0.1

	[SpeedLimits.GlassPoles]
		#Defines how fast sliding velocity changes
		# Default: 0.04
		# Range: 0.0 ~ 0.1
		acceleration = 0.04
		#Maximum climbing speed up the pole
		# Default: 0.08
		# Range: 0.0 ~ 0.4
		climbing = 0.08
		#Maximum sliding speed down the pole
		# Default: 0.64
		# Range: 0.0 ~ 0.8
		sliding = 0.64
		#Maximum spinning speed around the pole
		# Default: 0.16
		# Range: 0.0 ~ 0.2
		spinning = 0.16

	[SpeedLimits.WoodenPoles]
		#Defines how fast sliding velocity changes
		# Default: 0.04
		# Range: 0.0 ~ 0.1
		acceleration = 0.04
		#Maximum climbing speed up the pole
		# Default: 0.32
		# Range: 0.0 ~ 0.4
		climbing = 0.32
		#Maximum sliding speed down the pole
		# Default: 0.16
		# Range: 0.0 ~ 0.8
		sliding = 0.16
		#Maximum spinning speed around the pole
		# Default: 0.04
		# Range: 0.0 ~ 0.2
		spinning = 0.04
