[General]
	#Bypass the blocking when a player is an OP.
	opBypass = false
	#Bypass the blocking when a player is in creative mode.
	creativeBypass = false
	#Prevent these BLOCKS from being interacted with entirely (Only works if configured on client as well as server). If dimensions are desired, syntax is "modid:block$dimensions"
	no-interact = ["minecraft:enchanting_table"]
	#BLOCK id's in this list will not be harvestable. If dimensions are desired, syntax is "modid:block$dimension"
	no-harvest = ["minecraft:enchanting_table"]
	#BLOCK id's in this list will not be placeable and
	#will not spawn in the world nor return to the player. If dimensions are desired, syntax is "modid:block$dimensions"
	no-place = ["minecraft:enchanting_table"]
