#Friends
[friend_settings]
	#A list of users who can be chosen when it spawns a distant friend
	friends = ["FuriousDestroyer", "PinkSheepYT", "MHF_Herobrine", "Walter_White", "sigma_toe_nail", "SethBling", "minsnn", "Xyrol_l", "MHF_Villager", "Antvenom", "CaptainSparklez", "Dream"]
	#Add the players from the whitelist to the Friends list [default: true]
	addWhitelistPlayers = true

#Compat
[compat_settings]
	#Add players from a Player Mobs whitelist to the Friends list [default: false]
	playerMobsCompat = false
	#The player mobs Name Links, must start with https://whitelist.gorymoon.se
	playerMobsNameLinks = []
