#Give simple potions with an effect (awkward, mundane and thick) a unique effect color to set apart from water bottles.
#Default Value: true
colored_simple_potions = true
#Custom color overrides for mob effects, allows for restoring effect colors from previous Minecraft versions.
#Format for every entry is "<namespace>:<path>,<rgbcolor>". Tags are supported, must be in the format of "#<namespace>:<path>,<rgbcolor>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
#Default Value: []
mob_effect_color_overrides_raw = []
