#Amount of spaces to add at the beginning of an effect description.
#Default Value: 0
# Default: 0
# Range: 0 ~ 24
description_indentation = 0

[items]
	#Add effects to food tooltips.
	#Default Value: true
	food_effects = true
	#Items that should support descriptions for the effects on their inventory tooltip.
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color. Begin an entry with "!" to make sure it is excluded, useful e.g. when it has already been matched by another pattern.
	#Default Value: [minecraft:potion, minecraft:splash_potion, minecraft:lingering_potion, minecraft:tipped_arrow, minecraft:suspicious_stew]
	supported_items = ["minecraft:potion", "minecraft:splash_potion", "minecraft:lingering_potion", "minecraft:tipped_arrow", "minecraft:suspicious_stew"]
	#Only reveal effect description for items while any shift key is held.
	#Default Value: false
	shift_to_reveal = false
	#Add effect description to item tooltips.
	#Default Value: true
	description = true

[widgets]
	#Add the internal id of an effect to effect widget tooltips.
	#Default Value: false
	internal_id = false
	#Add effect description to effect widget tooltips in the survival and creative inventory screens.
	#Default Value: true
	description = true
	#Add the effect name and duration to large effect widget tooltips, even though the widget already contains both.
	#Default Value: NAME_AND_DURATION
	#Allowed Values: NAME_ONLY, NAME_AND_DURATION, NONE
	name_and_duration = "NAME_AND_DURATION"
	#Add attributes granted by an effect to effect widget tooltips.
	#Default Value: true
	attributes = true
	#Add the name of the mod that added an effect to effect widget tooltips.
	#Default Value: false
	mod_name = false
