#How many millieseconds it takes until an item is scaled to its full size on hover. 0 to disable.
# Default: 100
# Range: 0 ~ 1000
hoverAnimationTime = 100
#Allowed Values: LINEAR, QUAD_IN, QUAD_OUT, QUAD_INOUT, CUBIC_IN, CUBIC_OUT, CUBIC_INOUT, EXP_IN, EXP_OUT, EXP_INOUT, BACK_IN, BACK_OUT, BACK_INOUT, ELASTIC_IN, ELASTIC_OUT, ELASTIC_INOUT, BOUNCE_IN, BOUNCE_OUT, BOUNCE_INOUT, SINE_IN, SINE_OUT, SINE_INOUT, QUART_IN, QUART_OUT, QUART_INOUT, QUINT_IN, QUINT_OUT, QUINT_INOUT, CIRCLE_IN, CIRCLE_OUT, CIRCLE_INOUT
hoverAnimationCurve = "QUAD_INOUT"
#If the gray slot overlay (minecraft feature) should be rendered at all on hover. Default: false
itemHoverOverlay = false
#How many millieseconds it takes until an item has moved to its target (activated on shift click). 0 to disable.
# Default: 150
# Range: 0 ~ 1000
moveAnimationTime = 150
#Allowed Values: LINEAR, QUAD_IN, QUAD_OUT, QUAD_INOUT, CUBIC_IN, CUBIC_OUT, CUBIC_INOUT, EXP_IN, EXP_OUT, EXP_INOUT, BACK_IN, BACK_OUT, BACK_INOUT, ELASTIC_IN, ELASTIC_OUT, ELASTIC_INOUT, BOUNCE_IN, BOUNCE_OUT, BOUNCE_INOUT, SINE_IN, SINE_OUT, SINE_INOUT, QUART_IN, QUART_OUT, QUART_INOUT, QUINT_IN, QUINT_OUT, QUINT_INOUT, CIRCLE_IN, CIRCLE_OUT, CIRCLE_INOUT
moveAnimationCurve = "SINE_OUT"
#How many millieseconds it takes until an item has moved to its target (activated on shift click). 0 to disable.
# Default: 150
# Range: 0 ~ 1000
appearAnimationTime = 150
#Allowed Values: LINEAR, QUAD_IN, QUAD_OUT, QUAD_INOUT, CUBIC_IN, CUBIC_OUT, CUBIC_INOUT, EXP_IN, EXP_OUT, EXP_INOUT, BACK_IN, BACK_OUT, BACK_INOUT, ELASTIC_IN, ELASTIC_OUT, ELASTIC_INOUT, BOUNCE_IN, BOUNCE_OUT, BOUNCE_INOUT, SINE_IN, SINE_OUT, SINE_INOUT, QUART_IN, QUART_OUT, QUART_INOUT, QUINT_IN, QUINT_OUT, QUINT_INOUT, CIRCLE_IN, CIRCLE_OUT, CIRCLE_INOUT
appearAnimationCurve = "SINE_OUT"
#How many millieseconds it takes until the current item marker in the hotbar moved to its new location. 0 to disable.
# Default: 100
# Range: 0 ~ 1000
hotbarAnimationTime = 100
#Allowed Values: LINEAR, QUAD_IN, QUAD_OUT, QUAD_INOUT, CUBIC_IN, CUBIC_OUT, CUBIC_INOUT, EXP_IN, EXP_OUT, EXP_INOUT, BACK_IN, BACK_OUT, BACK_INOUT, ELASTIC_IN, ELASTIC_OUT, ELASTIC_INOUT, BOUNCE_IN, BOUNCE_OUT, BOUNCE_INOUT, SINE_IN, SINE_OUT, SINE_INOUT, QUART_IN, QUART_OUT, QUART_INOUT, QUINT_IN, QUINT_OUT, QUINT_INOUT, CIRCLE_IN, CIRCLE_OUT, CIRCLE_INOUT
hotbarAnimationCurve = "QUAD_INOUT"
#How many millieseconds it takes until the gui is fully opened. 0 to disable.
# Default: 90
# Range: 0 ~ 1000
openingAnimationTime = 0
#Allowed Values: LINEAR, QUAD_IN, QUAD_OUT, QUAD_INOUT, CUBIC_IN, CUBIC_OUT, CUBIC_INOUT, EXP_IN, EXP_OUT, EXP_INOUT, BACK_IN, BACK_OUT, BACK_INOUT, ELASTIC_IN, ELASTIC_OUT, ELASTIC_INOUT, BOUNCE_IN, BOUNCE_OUT, BOUNCE_INOUT, SINE_IN, SINE_OUT, SINE_INOUT, QUART_IN, QUART_OUT, QUART_INOUT, QUINT_IN, QUINT_OUT, QUINT_INOUT, CIRCLE_IN, CIRCLE_OUT, CIRCLE_INOUT
openingAnimationCurve = "SINE_OUT"
#Add class names (works with * at the end) which should be blacklisted from any animations.
#This is used to prevent visual issues with certain mods.
guiAnimationBlacklist = ["gregtech.*", "com.cleanroommc.modularui.*"]
