onCull = true
maxEntityEntities = 128
entitiesDistance = 64
QualityModes = "normal"
RenderWeather = "normal"
RenderTNTExplosions = true
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 57.594
chatFix = false
