#General settings
[general]
	#Defines the amount of uses the Gold TelePass has [Default: 15]
	# Default: 15
	# Range: > 0
	goldDurability = 150
	#Defines the amount of uses the Diamond TelePass has [Default: 1000]
	# Default: 1000
	# Range: > 0
	diamondDurability = 1000
